DROP TABLE "TB_PLAN_MAP";

CREATE TABLE "TB_PLAN_MAP" (
	"PLAN_MAP_NO"	NUMBER		NOT NULL,
	"PLAN_DAY"	DATE		NOT NULL,
	"ORDER_NO"	NUMBER		NOT NULL,
	"PLACE_NAME"	VARCHAR2(300)		NULL,
	"PLAN_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "TB_PLAN_MAP"."PLAN_MAP_NO" IS '지도번호';

COMMENT ON COLUMN "TB_PLAN_MAP"."PLAN_DAY" IS 'DAY1, DAY2';

COMMENT ON COLUMN "TB_PLAN_MAP"."ORDER_NO" IS '리스트 순서';

COMMENT ON COLUMN "TB_PLAN_MAP"."PLACE_NAME" IS '작성자가 작성한 장소명';

COMMENT ON COLUMN "TB_PLAN_MAP"."PLAN_NO" IS '일정번호';


ALTER TABLE "TB_PLAN_MAP" ADD CONSTRAINT "PK_TB_PLAN_MAP" PRIMARY KEY (
	"PLAN_XY_NO"
);

ALTER TABLE "TB_PLAN_MAP" ADD FOREIGN KEY (
	"PLAN_NO"
)
REFERENCES "TB_PLAN_OPTION" (
	"PLAN_NO"
);

CREATE SEQUENCE SEQ_PLANMAPNO
NOCACHE;