INSERT INTO TB_MEMBER(USER_NO, USER_ID, USER_PWD, USER_NAME, USER_NICK, USER_BIRTH, GENDER, EMAIL )
VALUES(SEQ_UNO.NEXTVAL, 'user01', 1234, '양현우','현우', '19940322', 'M', 'didaos123@naver.com');

SELECT USER_ID FROM TB_MEMBER WHERE USER_NAME ='양현우' AND EMAIL='didaos123@naver.com';